import { database } from "@/lib/application-db";
import { z } from "zod";
const schema = z.object({ id:z.string().uuid().optional(),company:z.string().trim().min(1).max(150),role:z.string().trim().min(1).max(180),stage:z.enum(["Wishlist","Applied","Interview","Offer","Rejected","Withdrawn"]),interview:z.string().refine(s=>s==="" || (/^\d{4}-\d{2}-\d{2}$/.test(s) && !isNaN(Date.parse(s)) && new Date(s).toISOString().slice(0,10)===s)),notes:z.string().max(5000) });
function failure(e:unknown) {console.error("Application storage failed",e);return Response.json({error:"Your changes couldn't be saved. Please try again."},{status:503});}
function sameOrigin(r:Request) {return !r.headers.get("origin") || r.headers.get("origin")===new URL(r.url).origin;}
export async function GET() {try {const rows=await database().prepare("SELECT * FROM applications ORDER BY created DESC, id DESC").all();return Response.json({applications:rows.results},{headers:{"Cache-Control":"no-store"}});}catch(e){return failure(e);}}
async function write(r:Request,update:boolean) {if(!sameOrigin(r))return new Response(null,{status:403});try {const parsed=schema.safeParse(await r.json());if(!parsed.success)return Response.json({error:"Check the company, role, stage, and interview date."},{status:400});const p=parsed.data;const db=database();if(update&&!p.id)return new Response(null,{status:400});const id=update?p.id!:crypto.randomUUID();let row;if(update){row=await db.prepare("UPDATE applications SET company=?, role=?, stage=?, interview=?, notes=? WHERE id=? RETURNING *").bind(p.company,p.role,p.stage,p.interview,p.notes,id).first();}else{row=await db.prepare("INSERT INTO applications (id,company,role,stage,interview,notes,created) VALUES (?,?,?,?,?,?,?) RETURNING *").bind(id,p.company,p.role,p.stage,p.interview,p.notes,new Date().toISOString()).first();}if(!row)return Response.json({error:"This application no longer exists. Refresh and try again."},{status:404});return Response.json({application:row},{status:update?200:201});}catch(e){return failure(e);}}
export const POST=(r:Request)=>write(r,false);
export const PUT=(r:Request)=>write(r,true);
export async function DELETE(r:Request){if(!sameOrigin(r))return new Response(null,{status:403});try{const p=z.object({id:z.string().uuid()}).safeParse(await r.json());if(!p.success)return new Response(null,{status:400});await database().prepare("DELETE FROM applications WHERE id=?").bind(p.data.id).run();return Response.json({ok:true});}catch(e){return failure(e);}}

